#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

md5sum packages/packages.json > packages/manifest
echo "Updated manifest file"
git add packages/manifest
git commit -m "Updated manifest file" >> /dev/null
exit 1
