[package]
name = "example"

[apt]
available = false
name = "example"

[pacman]
available = false
name = "example"

[pipx]
available = false
name = "example"
# git = git+https://... Use this for github installs

[gem]
available = false
name = "example"

[snap]
available = false
name = "example"

[flatpak]
available = false
name = "example"

[cargo]
available = false
name = "example"

[yay]
available = false
name = "example"
