[package]
name = "example"

[apt]
available = true
name = "example"

[pacman]
available = true
name = "example"

[pipx]
available = true
name = "example"

[gem]
available = true
name = "example"

[cargo]
available = true
name = "example"